In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
from PIL import Image
import requests
from io import BytesIO
from patsy import dmatrices

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier

In [117]:
df_raw = pd.read_csv("./data/Credit.csv")

In [118]:
df_raw.shape

(400, 12)

In [119]:
df_raw.head()

,Unnamed: 0,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331

In [120]:
df = df_raw.astype({ 'Gender': 'category', 'Student': 'category', 'Married': 'category', 'Ethnicity': 'category' }).drop('Unnamed: 0', axis=1)

In [121]:
df.dtypes

Income        float64
Limit           int64
Rating          int64
Cards           int64
Age             int64
Education       int64
Gender       category
Student      category
Married      category
Ethnicity    category
Balance         int64
dtype: object

In [122]:
df.shape

(400, 11)

In [123]:
def train_model(df, formula, model):
    y, x = dmatrices(formula, data=df, return_type='dataframe') 
    Y = y.values.ravel()
    X = x.values
#     print(X.shape)
#     print(Y.shape)
    kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=1)
    cv_results = model_selection.cross_val_score(model, y, x, cv=kfold, scoring='accuracy')
    msg = "%s:     mean: %f       std: %f" % (name, cv_results.mean(), cv_results.std())
    print(msg)

## Logistic regression

In [127]:
df['IncomeGt50'] = df.apply(lambda row: 'Yes' if row['Income'] > 50 else 'No', axis=1)

In [128]:
df.astype({'IncomeGt50': 'category'})

,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance,IncomeGt50
0,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333,No
1,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903,Yes
2,104.593,7075,514,4,71,11,Male,No,No,Asian,580,Yes
3,148.924,9504,681,3,36,11,Female,No,No,Asian,964,Yes
4,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,Male,No,Yes,Caucasian,560,No
396,13.364,3838,296,5,65,17,Male,No,No,African American,480,No
397,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138,Yes
398,37.728,2525,192,1,44,13,Male,No,Yes,Caucasian,0,No
399,18.701,5524,415,5,64,7,Female,No,No,Asian,966,No

In [129]:
train_model(df, "IncomeGt50 ~ Balance", LogisticRegression())

ValueError:
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1138, in fit
    X, y = self._validate_data(
  File "/usr/lib/python3.10/site-packages/sklearn/base.py", line 596, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1090, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
  File "/usr/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1111, in _check_y
    y = column_or_1d(y, warn=True)
  File "/usr/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1156, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (360, 2) instead.